# Generated by Django 4.0.6 on 2022-08-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='เบอร์มือถือ'),
        ),
        migrations.AlterField(
            model_name='users',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำแหน่ง'),
        ),
    ]
