# Generated by Django 4.0.6 on 2022-07-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_is_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_approve',
            field=models.BooleanField(),
        ),
    ]
