# Generated by Django 4.0.6 on 2022-08-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_mobile_phone_alter_users_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_approve',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
