# Generated by Django 4.0.6 on 2022-08-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dutytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_shortname', models.CharField(max_length=50, verbose_name='หน้าที่เวร')),
                ('duty_name', models.CharField(max_length=200, verbose_name='หน้าที่เวร')),
                ('detail', models.CharField(blank=True, max_length=100, verbose_name='รายละเอียดหน้าที่เวร')),
                ('edit_date', models.DateTimeField(blank=True, verbose_name='แก้ไขล่าสุด')),
                ('creat_date', models.DateTimeField(blank=True, verbose_name='สร้างเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'Duty : ประเภทการเข้าเวร',
            },
        ),
        migrations.CreateModel(
            name='exception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=100, null=True, verbose_name='รายละเอียดการงดเวร')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='เริ่ม')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='สิ้นสุด')),
                ('edit_date', models.DateTimeField(blank=True, null=True, verbose_name='แก้ไขล่าสุด')),
                ('creat_date', models.DateTimeField(blank=True, null=True, verbose_name='สร้างเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'exception : งดเวร',
            },
        ),
        migrations.CreateModel(
            name='ondutylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_onduty', models.DateTimeField(blank=True, null=True, verbose_name='วัน-เวลา เริ่มเข้าเวร')),
                ('end_onduty', models.DateTimeField(blank=True, null=True, verbose_name='วัน-เวลา สิ้นสุด')),
                ('edit_date', models.DateTimeField(blank=True, null=True, verbose_name='แก้ไขล่าสุด')),
                ('creat_date', models.DateTimeField(blank=True, null=True, verbose_name='สร้างเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'dutyhd : ตารางเวร',
            },
        ),
        migrations.CreateModel(
            name='timeonduty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(blank=True, null=True, verbose_name='สร้างเมื่อ')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='สร้างเมื่อ')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='สร้างเมื่อ')),
                ('detail', models.CharField(blank=True, max_length=100, null=True, verbose_name='รายละเอียดการงดเวร')),
                ('edit_date', models.DateTimeField(blank=True, null=True, verbose_name='แก้ไขล่าสุด')),
                ('creat_date', models.DateTimeField(blank=True, null=True, verbose_name='สร้างเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'timeonduty : วัน-เวลา เข้าเวร',
            },
        ),
    ]
