# Generated by Django 4.0.6 on 2022-07-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dutytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_shortname', models.CharField(max_length=50, verbose_name='หน้าที่เวร')),
                ('duty_name', models.CharField(max_length=200, verbose_name='หน้าที่เวร')),
                ('detail', models.CharField(blank=True, max_length=100, verbose_name='รายละเอียดหน้าที่เวร')),
                ('edit_date', models.DateTimeField(blank=True, verbose_name='แก้ไขล่าสุด')),
                ('creat_date', models.DateTimeField(blank=True, verbose_name='สร้างเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'Duty : ประเภทการเข้าเวร',
            },
        ),
    ]
