# Generated by Django 4.0.6 on 2022-07-28 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manageduty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=100, verbose_name='รายละเอียดหน้าที่เวร')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='เริ่ม')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='สิ้นสุด')),
                ('edit_date', models.DateTimeField(blank=True, verbose_name='แก้ไขล่าสุด')),
                ('creat_date', models.DateTimeField(blank=True, verbose_name='สร้างเมื่อ')),
                ('users_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
        ),
    ]
