# Generated by Django 4.0.6 on 2022-08-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageduty', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exception',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='สิ้นสุด'),
        ),
        migrations.AlterField(
            model_name='exception',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='เริ่ม'),
        ),
    ]
