# Generated by Django 4.0.6 on 2022-07-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageduty', '0003_alter_exception_options_alter_exception_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutyhd',
            name='users_id',
        ),
    ]
