# Generated by Django 4.0.6 on 2022-07-28 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manageduty', '0004_remove_dutyhd_users_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ondutylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onduty_date', models.DateTimeField(blank=True, verbose_name='แก้ไขล่าสุด')),
                ('edit_date', models.DateTimeField(blank=True, verbose_name='แก้ไขล่าสุด')),
                ('creat_date', models.DateTimeField(blank=True, verbose_name='สร้างเมื่อ')),
                ('users_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'verbose_name_plural': 'dutyhd : ตารางเวร',
            },
        ),
        migrations.DeleteModel(
            name='dutyhd',
        ),
    ]
