# Generated by Django 4.0.6 on 2022-07-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageduty', '0006_remove_ondutylist_onduty_date_ondutylist_end_onduty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeonduty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(blank=True, null=True, verbose_name='สร้างเมื่อ')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='สร้างเมื่อ')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='สร้างเมื่อ')),
                ('detail', models.CharField(blank=True, max_length=100, null=True, verbose_name='รายละเอียดการงดเวร')),
            ],
            options={
                'verbose_name_plural': 'timeonduty : วัน-เวลา เข้าเวร',
            },
        ),
    ]
